In [1]:
import csv
open_file = open("Student Report.csv", mode = "r")
open_file

In [2]:
read = csv.reader(open_file)
read

In [3]:
data = list(read)
data

[['roll no', 'Name', 'Chemistry', 'Physics', 'Math'],
 ['101', 'Aliza', '50', '23', '87'],
 ['102', 'Fareed', '45', '24', '88'],
 ['103', 'Basit', '46', '25', '89'],
 ['104', 'Abdullah', '47', '26', '90'],
 ['105', 'Ali', '48', '27', '67'],
 ['106', 'Mubashir', '49', '28', '68'],
 ['107', 'Waleed', '50', '29', '69'],
 ['108', 'Mansoor', '51', '30', '70'],
 ['109', 'Zain', '52', '31', '71'],
 ['110', 'Mohsin', '53', '67', '72'],
 ['111', 'Shahmeer', '54', '68', '73'],
 ['112', 'Rao', '55', '69', '74'],
 ['113', 'Aurangzeb', '56', '70', '75'],
 ['114', 'Zeeshan', '57', '71', '76'],
 ['115', 'Hamna', '58', '72', '77'],
 ['116', 'Hamza', '59', '73', '78'],
 ['117', 'Khalid', '60', '74', '79'],
 ['118', 'Behroz', '61', '75', '80'],
 ['119', 'Justin', '62', '76', '81'],
 ['120', 'Danish', '63', '77', '82'],
 ['121', 'Kainat', '64', '78', '83'],
 ['122', 'Sameer', '65', '79', '84'],
 ['123', 'Raza', '66', '80', '85'],
 ['124', 'Kumar', '67', '81', '86'],
 ['125', 'Komal', '68', '82', '87'],
 ['126', 'Erum', '69', '83', '88'],
 ['127', 'Faiza', '70', '84', '89'],
 ['128', 'Saeed', '71', '85', '90'],
 ['129', 'Waqar', '72', '86', '91'],
 ['130', 'Wali', '73', '87', '92'],
 ['131', 'Wajid', '74', '88', '93'],
 ['132', 'Waseeb', '75', '89', '94'],
 ['133', 'Shiza', '76', '90', '95'],
 ['134', 'Shabina', '77', '91', '96'],
 ['135', 'Shazain', '78', '55', '97'],
 ['136', 'Lubna', '79', '61', '98'],
 ['137', 'Laiba', '80', '88', '78'],
 ['138', 'Khursheed', '81', '56', '45'],
 ['139', 'Ali', '82', '89', '46'],
 ['140', 'Aiza', '83', '45', '89'],
 ['141', 'Aiman', '84', '92', '78'],
 ['142', 'Yasmeen', '85', '36', '56'],
 ['143', 'Tasbeel', '86', '78', '78'],
 ['144', 'Laraib', '87', '56', '54'],
 ['145', 'Saleem', '88', '78', '78'],
 ['146', 'Bismil', '89', '89', '46'],
 ['147', 'Batool', '90', '56', '79'],
 ['148', 'Iqra', '91', '33', '46'],
 ['149', 'Zarnish', '92', '78', '45'],
 ['150', 'Zara', '83', '45', '56']]

In [4]:
header = data[0]
header

['roll no', 'Name', 'Chemistry', 'Physics', 'Math']

In [5]:
student_report = data[1:]
student_report

[['101', 'Aliza', '50', '23', '87'],
 ['102', 'Fareed', '45', '24', '88'],
 ['103', 'Basit', '46', '25', '89'],
 ['104', 'Abdullah', '47', '26', '90'],
 ['105', 'Ali', '48', '27', '67'],
 ['106', 'Mubashir', '49', '28', '68'],
 ['107', 'Waleed', '50', '29', '69'],
 ['108', 'Mansoor', '51', '30', '70'],
 ['109', 'Zain', '52', '31', '71'],
 ['110', 'Mohsin', '53', '67', '72'],
 ['111', 'Shahmeer', '54', '68', '73'],
 ['112', 'Rao', '55', '69', '74'],
 ['113', 'Aurangzeb', '56', '70', '75'],
 ['114', 'Zeeshan', '57', '71', '76'],
 ['115', 'Hamna', '58', '72', '77'],
 ['116', 'Hamza', '59', '73', '78'],
 ['117', 'Khalid', '60', '74', '79'],
 ['118', 'Behroz', '61', '75', '80'],
 ['119', 'Justin', '62', '76', '81'],
 ['120', 'Danish', '63', '77', '82'],
 ['121', 'Kainat', '64', '78', '83'],
 ['122', 'Sameer', '65', '79', '84'],
 ['123', 'Raza', '66', '80', '85'],
 ['124', 'Kumar', '67', '81', '86'],
 ['125', 'Komal', '68', '82', '87'],
 ['126', 'Erum', '69', '83', '88'],
 ['127', 'Faiza', '70', '84', '89'],
 ['128', 'Saeed', '71', '85', '90'],
 ['129', 'Waqar', '72', '86', '91'],
 ['130', 'Wali', '73', '87', '92'],
 ['131', 'Wajid', '74', '88', '93'],
 ['132', 'Waseeb', '75', '89', '94'],
 ['133', 'Shiza', '76', '90', '95'],
 ['134', 'Shabina', '77', '91', '96'],
 ['135', 'Shazain', '78', '55', '97'],
 ['136', 'Lubna', '79', '61', '98'],
 ['137', 'Laiba', '80', '88', '78'],
 ['138', 'Khursheed', '81', '56', '45'],
 ['139', 'Ali', '82', '89', '46'],
 ['140', 'Aiza', '83', '45', '89'],
 ['141', 'Aiman', '84', '92', '78'],
 ['142', 'Yasmeen', '85', '36', '56'],
 ['143', 'Tasbeel', '86', '78', '78'],
 ['144', 'Laraib', '87', '56', '54'],
 ['145', 'Saleem', '88', '78', '78'],
 ['146', 'Bismil', '89', '89', '46'],
 ['147', 'Batool', '90', '56', '79'],
 ['148', 'Iqra', '91', '33', '46'],
 ['149', 'Zarnish', '92', '78', '45'],
 ['150', 'Zara', '83', '45', '56']]

In [6]:
student_report[0][3]

'23'

In [7]:
phy_marks = []
for i in student_report:
    phy_marks.append(float(i[3]))

phy_marks

[23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 55.0,
 61.0,
 88.0,
 56.0,
 89.0,
 45.0,
 92.0,
 36.0,
 78.0,
 56.0,
 78.0,
 89.0,
 56.0,
 33.0,
 78.0,
 45.0]

In [8]:
sum(phy_marks)

3253.0

In [9]:
phy_marks = [float(i[3]) for i in student_report]
phy_marks

[23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 55.0,
 61.0,
 88.0,
 56.0,
 89.0,
 45.0,
 92.0,
 36.0,
 78.0,
 56.0,
 78.0,
 89.0,
 56.0,
 33.0,
 78.0,
 45.0]

In [10]:
sum(phy_marks)

3253.0

In [11]:
len(phy_marks)

50

In [12]:
Avg_phy_marks = sum(phy_marks)/len(phy_marks)
Avg_phy_marks

65.06

In [13]:
student_report

[['101', 'Aliza', '50', '23', '87'],
 ['102', 'Fareed', '45', '24', '88'],
 ['103', 'Basit', '46', '25', '89'],
 ['104', 'Abdullah', '47', '26', '90'],
 ['105', 'Ali', '48', '27', '67'],
 ['106', 'Mubashir', '49', '28', '68'],
 ['107', 'Waleed', '50', '29', '69'],
 ['108', 'Mansoor', '51', '30', '70'],
 ['109', 'Zain', '52', '31', '71'],
 ['110', 'Mohsin', '53', '67', '72'],
 ['111', 'Shahmeer', '54', '68', '73'],
 ['112', 'Rao', '55', '69', '74'],
 ['113', 'Aurangzeb', '56', '70', '75'],
 ['114', 'Zeeshan', '57', '71', '76'],
 ['115', 'Hamna', '58', '72', '77'],
 ['116', 'Hamza', '59', '73', '78'],
 ['117', 'Khalid', '60', '74', '79'],
 ['118', 'Behroz', '61', '75', '80'],
 ['119', 'Justin', '62', '76', '81'],
 ['120', 'Danish', '63', '77', '82'],
 ['121', 'Kainat', '64', '78', '83'],
 ['122', 'Sameer', '65', '79', '84'],
 ['123', 'Raza', '66', '80', '85'],
 ['124', 'Kumar', '67', '81', '86'],
 ['125', 'Komal', '68', '82', '87'],
 ['126', 'Erum', '69', '83', '88'],
 ['127', 'Faiza', '70', '84', '89'],
 ['128', 'Saeed', '71', '85', '90'],
 ['129', 'Waqar', '72', '86', '91'],
 ['130', 'Wali', '73', '87', '92'],
 ['131', 'Wajid', '74', '88', '93'],
 ['132', 'Waseeb', '75', '89', '94'],
 ['133', 'Shiza', '76', '90', '95'],
 ['134', 'Shabina', '77', '91', '96'],
 ['135', 'Shazain', '78', '55', '97'],
 ['136', 'Lubna', '79', '61', '98'],
 ['137', 'Laiba', '80', '88', '78'],
 ['138', 'Khursheed', '81', '56', '45'],
 ['139', 'Ali', '82', '89', '46'],
 ['140', 'Aiza', '83', '45', '89'],
 ['141', 'Aiman', '84', '92', '78'],
 ['142', 'Yasmeen', '85', '36', '56'],
 ['143', 'Tasbeel', '86', '78', '78'],
 ['144', 'Laraib', '87', '56', '54'],
 ['145', 'Saleem', '88', '78', '78'],
 ['146', 'Bismil', '89', '89', '46'],
 ['147', 'Batool', '90', '56', '79'],
 ['148', 'Iqra', '91', '33', '46'],
 ['149', 'Zarnish', '92', '78', '45'],
 ['150', 'Zara', '83', '45', '56']]

In [14]:
for marks in student_report:
    phy = float(marks[3])
    maths = float(marks[4])
    chem = float(marks[2])
    total_marks = chem+phy+maths
    marks.append(total_marks)

In [15]:
student_report

[['101', 'Aliza', '50', '23', '87', 160.0],
 ['102', 'Fareed', '45', '24', '88', 157.0],
 ['103', 'Basit', '46', '25', '89', 160.0],
 ['104', 'Abdullah', '47', '26', '90', 163.0],
 ['105', 'Ali', '48', '27', '67', 142.0],
 ['106', 'Mubashir', '49', '28', '68', 145.0],
 ['107', 'Waleed', '50', '29', '69', 148.0],
 ['108', 'Mansoor', '51', '30', '70', 151.0],
 ['109', 'Zain', '52', '31', '71', 154.0],
 ['110', 'Mohsin', '53', '67', '72', 192.0],
 ['111', 'Shahmeer', '54', '68', '73', 195.0],
 ['112', 'Rao', '55', '69', '74', 198.0],
 ['113', 'Aurangzeb', '56', '70', '75', 201.0],
 ['114', 'Zeeshan', '57', '71', '76', 204.0],
 ['115', 'Hamna', '58', '72', '77', 207.0],
 ['116', 'Hamza', '59', '73', '78', 210.0],
 ['117', 'Khalid', '60', '74', '79', 213.0],
 ['118', 'Behroz', '61', '75', '80', 216.0],
 ['119', 'Justin', '62', '76', '81', 219.0],
 ['120', 'Danish', '63', '77', '82', 222.0],
 ['121', 'Kainat', '64', '78', '83', 225.0],
 ['122', 'Sameer', '65', '79', '84', 228.0],
 ['123', 'Raza', '66', '80', '85', 231.0],
 ['124', 'Kumar', '67', '81', '86', 234.0],
 ['125', 'Komal', '68', '82', '87', 237.0],
 ['126', 'Erum', '69', '83', '88', 240.0],
 ['127', 'Faiza', '70', '84', '89', 243.0],
 ['128', 'Saeed', '71', '85', '90', 246.0],
 ['129', 'Waqar', '72', '86', '91', 249.0],
 ['130', 'Wali', '73', '87', '92', 252.0],
 ['131', 'Wajid', '74', '88', '93', 255.0],
 ['132', 'Waseeb', '75', '89', '94', 258.0],
 ['133', 'Shiza', '76', '90', '95', 261.0],
 ['134', 'Shabina', '77', '91', '96', 264.0],
 ['135', 'Shazain', '78', '55', '97', 230.0],
 ['136', 'Lubna', '79', '61', '98', 238.0],
 ['137', 'Laiba', '80', '88', '78', 246.0],
 ['138', 'Khursheed', '81', '56', '45', 182.0],
 ['139', 'Ali', '82', '89', '46', 217.0],
 ['140', 'Aiza', '83', '45', '89', 217.0],
 ['141', 'Aiman', '84', '92', '78', 254.0],
 ['142', 'Yasmeen', '85', '36', '56', 177.0],
 ['143', 'Tasbeel', '86', '78', '78', 242.0],
 ['144', 'Laraib', '87', '56', '54', 197.0],
 ['145', 'Saleem', '88', '78', '78', 244.0],
 ['146', 'Bismil', '89', '89', '46', 224.0],
 ['147', 'Batool', '90', '56', '79', 225.0],
 ['148', 'Iqra', '91', '33', '46', 170.0],
 ['149', 'Zarnish', '92', '78', '45', 215.0],
 ['150', 'Zara', '83', '45', '56', 184.0]]

In [16]:
for percent in student_report:
    phy = float(percent[3])
    maths = float(percent[4])
    chem = float(percent[2])
    percentage = round((chem+phy+maths)/300*100,2)
    percent_with_sign = f"{percentage}%"
    percent.append(percent_with_sign)

In [17]:
student_report

[['101', 'Aliza', '50', '23', '87', 160.0, '53.33%'],
 ['102', 'Fareed', '45', '24', '88', 157.0, '52.33%'],
 ['103', 'Basit', '46', '25', '89', 160.0, '53.33%'],
 ['104', 'Abdullah', '47', '26', '90', 163.0, '54.33%'],
 ['105', 'Ali', '48', '27', '67', 142.0, '47.33%'],
 ['106', 'Mubashir', '49', '28', '68', 145.0, '48.33%'],
 ['107', 'Waleed', '50', '29', '69', 148.0, '49.33%'],
 ['108', 'Mansoor', '51', '30', '70', 151.0, '50.33%'],
 ['109', 'Zain', '52', '31', '71', 154.0, '51.33%'],
 ['110', 'Mohsin', '53', '67', '72', 192.0, '64.0%'],
 ['111', 'Shahmeer', '54', '68', '73', 195.0, '65.0%'],
 ['112', 'Rao', '55', '69', '74', 198.0, '66.0%'],
 ['113', 'Aurangzeb', '56', '70', '75', 201.0, '67.0%'],
 ['114', 'Zeeshan', '57', '71', '76', 204.0, '68.0%'],
 ['115', 'Hamna', '58', '72', '77', 207.0, '69.0%'],
 ['116', 'Hamza', '59', '73', '78', 210.0, '70.0%'],
 ['117', 'Khalid', '60', '74', '79', 213.0, '71.0%'],
 ['118', 'Behroz', '61', '75', '80', 216.0, '72.0%'],
 ['119', 'Justin', '62', '76', '81', 219.0, '73.0%'],
 ['120', 'Danish', '63', '77', '82', 222.0, '74.0%'],
 ['121', 'Kainat', '64', '78', '83', 225.0, '75.0%'],
 ['122', 'Sameer', '65', '79', '84', 228.0, '76.0%'],
 ['123', 'Raza', '66', '80', '85', 231.0, '77.0%'],
 ['124', 'Kumar', '67', '81', '86', 234.0, '78.0%'],
 ['125', 'Komal', '68', '82', '87', 237.0, '79.0%'],
 ['126', 'Erum', '69', '83', '88', 240.0, '80.0%'],
 ['127', 'Faiza', '70', '84', '89', 243.0, '81.0%'],
 ['128', 'Saeed', '71', '85', '90', 246.0, '82.0%'],
 ['129', 'Waqar', '72', '86', '91', 249.0, '83.0%'],
 ['130', 'Wali', '73', '87', '92', 252.0, '84.0%'],
 ['131', 'Wajid', '74', '88', '93', 255.0, '85.0%'],
 ['132', 'Waseeb', '75', '89', '94', 258.0, '86.0%'],
 ['133', 'Shiza', '76', '90', '95', 261.0, '87.0%'],
 ['134', 'Shabina', '77', '91', '96', 264.0, '88.0%'],
 ['135', 'Shazain', '78', '55', '97', 230.0, '76.67%'],
 ['136', 'Lubna', '79', '61', '98', 238.0, '79.33%'],
 ['137', 'Laiba', '80', '88', '78', 246.0, '82.0%'],
 ['138', 'Khursheed', '81', '56', '45', 182.0, '60.67%'],
 ['139', 'Ali', '82', '89', '46', 217.0, '72.33%'],
 ['140', 'Aiza', '83', '45', '89', 217.0, '72.33%'],
 ['141', 'Aiman', '84', '92', '78', 254.0, '84.67%'],
 ['142', 'Yasmeen', '85', '36', '56', 177.0, '59.0%'],
 ['143', 'Tasbeel', '86', '78', '78', 242.0, '80.67%'],
 ['144', 'Laraib', '87', '56', '54', 197.0, '65.67%'],
 ['145', 'Saleem', '88', '78', '78', 244.0, '81.33%'],
 ['146', 'Bismil', '89', '89', '46', 224.0, '74.67%'],
 ['147', 'Batool', '90', '56', '79', 225.0, '75.0%'],
 ['148', 'Iqra', '91', '33', '46', 170.0, '56.67%'],
 ['149', 'Zarnish', '92', '78', '45', 215.0, '71.67%'],
 ['150', 'Zara', '83', '45', '56', 184.0, '61.33%']]

In [18]:
for percent in student_report:
    phy = float(percent[3])
    maths = float(percent[4])
    chem = float(percent[2])
    percentage = round((chem+phy+maths)/300*100,2)
    percent_with_sign = f"{percentage}%"
    if percentage >= 80:
        percent.append("A")
    elif percentage >= 70:
        percent.append("B")
    elif percentage >= 60:
        percent.append("C")
    elif percentage >= 50:
        percent.append("D")
    else:
        percent.append("FAILED")

In [19]:
student_report

[['101', 'Aliza', '50', '23', '87', 160.0, '53.33%', 'D'],
 ['102', 'Fareed', '45', '24', '88', 157.0, '52.33%', 'D'],
 ['103', 'Basit', '46', '25', '89', 160.0, '53.33%', 'D'],
 ['104', 'Abdullah', '47', '26', '90', 163.0, '54.33%', 'D'],
 ['105', 'Ali', '48', '27', '67', 142.0, '47.33%', 'FAILED'],
 ['106', 'Mubashir', '49', '28', '68', 145.0, '48.33%', 'FAILED'],
 ['107', 'Waleed', '50', '29', '69', 148.0, '49.33%', 'FAILED'],
 ['108', 'Mansoor', '51', '30', '70', 151.0, '50.33%', 'D'],
 ['109', 'Zain', '52', '31', '71', 154.0, '51.33%', 'D'],
 ['110', 'Mohsin', '53', '67', '72', 192.0, '64.0%', 'C'],
 ['111', 'Shahmeer', '54', '68', '73', 195.0, '65.0%', 'C'],
 ['112', 'Rao', '55', '69', '74', 198.0, '66.0%', 'C'],
 ['113', 'Aurangzeb', '56', '70', '75', 201.0, '67.0%', 'C'],
 ['114', 'Zeeshan', '57', '71', '76', 204.0, '68.0%', 'C'],
 ['115', 'Hamna', '58', '72', '77', 207.0, '69.0%', 'C'],
 ['116', 'Hamza', '59', '73', '78', 210.0, '70.0%', 'B'],
 ['117', 'Khalid', '60', '74', '79', 213.0, '71.0%', 'B'],
 ['118', 'Behroz', '61', '75', '80', 216.0, '72.0%', 'B'],
 ['119', 'Justin', '62', '76', '81', 219.0, '73.0%', 'B'],
 ['120', 'Danish', '63', '77', '82', 222.0, '74.0%', 'B'],
 ['121', 'Kainat', '64', '78', '83', 225.0, '75.0%', 'B'],
 ['122', 'Sameer', '65', '79', '84', 228.0, '76.0%', 'B'],
 ['123', 'Raza', '66', '80', '85', 231.0, '77.0%', 'B'],
 ['124', 'Kumar', '67', '81', '86', 234.0, '78.0%', 'B'],
 ['125', 'Komal', '68', '82', '87', 237.0, '79.0%', 'B'],
 ['126', 'Erum', '69', '83', '88', 240.0, '80.0%', 'A'],
 ['127', 'Faiza', '70', '84', '89', 243.0, '81.0%', 'A'],
 ['128', 'Saeed', '71', '85', '90', 246.0, '82.0%', 'A'],
 ['129', 'Waqar', '72', '86', '91', 249.0, '83.0%', 'A'],
 ['130', 'Wali', '73', '87', '92', 252.0, '84.0%', 'A'],
 ['131', 'Wajid', '74', '88', '93', 255.0, '85.0%', 'A'],
 ['132', 'Waseeb', '75', '89', '94', 258.0, '86.0%', 'A'],
 ['133', 'Shiza', '76', '90', '95', 261.0, '87.0%', 'A'],
 ['134', 'Shabina', '77', '91', '96', 264.0, '88.0%', 'A'],
 ['135', 'Shazain', '78', '55', '97', 230.0, '76.67%', 'B'],
 ['136', 'Lubna', '79', '61', '98', 238.0, '79.33%', 'B'],
 ['137', 'Laiba', '80', '88', '78', 246.0, '82.0%', 'A'],
 ['138', 'Khursheed', '81', '56', '45', 182.0, '60.67%', 'C'],
 ['139', 'Ali', '82', '89', '46', 217.0, '72.33%', 'B'],
 ['140', 'Aiza', '83', '45', '89', 217.0, '72.33%', 'B'],
 ['141', 'Aiman', '84', '92', '78', 254.0, '84.67%', 'A'],
 ['142', 'Yasmeen', '85', '36', '56', 177.0, '59.0%', 'D'],
 ['143', 'Tasbeel', '86', '78', '78', 242.0, '80.67%', 'A'],
 ['144', 'Laraib', '87', '56', '54', 197.0, '65.67%', 'C'],
 ['145', 'Saleem', '88', '78', '78', 244.0, '81.33%', 'A'],
 ['146', 'Bismil', '89', '89', '46', 224.0, '74.67%', 'B'],
 ['147', 'Batool', '90', '56', '79', 225.0, '75.0%', 'B'],
 ['148', 'Iqra', '91', '33', '46', 170.0, '56.67%', 'D'],
 ['149', 'Zarnish', '92', '78', '45', 215.0, '71.67%', 'B'],
 ['150', 'Zara', '83', '45', '56', 184.0, '61.33%', 'C']]

In [31]:
open_file = open("student_report.csv",mode='w',newline='')
open_file

In [34]:
writer = csv.writer(open_file)
writer

In [35]:
open_file.close()